site_name: MkDocs Material Documentation
repo_url: https://github.com/jcalo-git/mkdocs
repo_name: jcalo-git/mkdocs
edit_uri: edit/main/docs/

theme:
  features:
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  name: material
  palette:
   # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
